// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA-cUK5alKAPrOWleLFqhRcCAfisT20F0',
    appId: '1:873280351713:web:ce72f1b1df10a73daf76a0',
    messagingSenderId: '873280351713',
    projectId: 'cinoscope-9075a',
    authDomain: 'cinoscope-9075a.firebaseapp.com',
    storageBucket: 'cinoscope-9075a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfUBkKXRbYDiEut2Jijy1lIn7dfnM0lA4',
    appId: '1:873280351713:android:6affceff5d1cc5aaaf76a0',
    messagingSenderId: '873280351713',
    projectId: 'cinoscope-9075a',
    storageBucket: 'cinoscope-9075a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxZzUryHaBQINcg1rnpGTCA1lh5SKyv70',
    appId: '1:873280351713:ios:fe55875f7f54b773af76a0',
    messagingSenderId: '873280351713',
    projectId: 'cinoscope-9075a',
    storageBucket: 'cinoscope-9075a.firebasestorage.app',
    iosBundleId: 'com.example.cinescope',
  );
}
